[[plugins]]
  package = "react"
  package = "react-dom"

[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
